# Generated by Django 6.0.2 on 2026-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], max_length=10, null=True),
        ),
    ]
