# Generated by Django 6.0.2 on 2026-02-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_image', models.ImageField(upload_to='banners/desktop/')),
                ('mobile_image', models.ImageField(upload_to='banners/mobile/')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_label', models.CharField(max_length=50)),
                ('link_url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
