# Generated by Django 6.0.2 on 2026-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='desktop_image',
            field=models.ImageField(max_length=500, upload_to='banners/desktop/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(max_length=500, upload_to='banners/mobile/'),
        ),
    ]
