# Generated by Django 6.0.2 on 2026-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='The Crunch', max_length=255)),
                ('email_address', models.EmailField(default='hello@thecrunch.com', max_length=254)),
                ('phone_number', models.CharField(default='+91 98765 43210', max_length=20)),
                ('physical_address', models.TextField(default='Kakkanad, Kochi, Kerala')),
                ('map_link', models.URLField(blank=True, max_length=500, null=True)),
                ('delivery_radius', models.PositiveIntegerField(default=5, help_text='In KM')),
                ('footer_description', models.TextField(blank=True, null=True)),
                ('working_hours_mon_sat', models.CharField(default='10:00 AM - 11:00 PM', max_length=100)),
                ('working_hours_sunday', models.CharField(default='09:00 AM - 12:00 AM', max_length=100)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True)),
                ('whatsapp_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
