# Generated by Django 6.0.2 on 2026-03-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='delivery_radius',
            field=models.PositiveIntegerField(default=0, help_text='In KM'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='physical_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='restaurant_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='working_hours_mon_sat',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='working_hours_sunday',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
