# Generated by Django 6.0.2 on 2026-03-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesetting_delivery_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='map_link',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
