# Generated by Django 6.0.2 on 2026-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_remove_sitesetting_map_link_sitesetting_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
