# Generated by Django 6.0.2 on 2026-03-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesetting_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Format: HH:MM:SS', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Format: HH:MM:SS', null=True),
        ),
    ]
