# Generated by Django 6.0.2 on 2026-03-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesetting_closing_time_sitesetting_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_manually_open',
            field=models.BooleanField(default=True, help_text='Turn OFF to manually close the restaurant immediately.'),
        ),
    ]
