# Generated by Django 6.0.2 on 2026-03-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesetting_is_manually_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='delivery_radius',
            field=models.FloatField(default=0, help_text='In KM'),
        ),
    ]
