# Generated by Django 6.0.2 on 2026-02-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_best_seller',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='tag',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Actual ₹'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dietary_preference',
            field=models.CharField(choices=[('VEG', 'Veg'), ('NON-VEG', 'Non-Veg')], default='VEG', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Offer ₹'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='inventory.section'),
        ),
    ]
