# Generated by Django 6.0.2 on 2026-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_section_remove_menuitem_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('ALL', 'All'), ('BANNER', 'Banner'), ('COMBO MENU', 'Combo Menu'), ('BEST SELLER', 'Best Seller'), ("TODAY'S SPECIAL", "Today's Special"), ('OTHERS', 'Others')], default='ALL', max_length=50),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
