# Generated by Django 6.0.2 on 2026-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_menuitem_section_delete_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('ALL', 'All'), ('BANNER', 'Banner'), ('COMBO MENU', 'Combo Menu'), ('BEST SELLER', 'Best Seller'), ('TODAYS SPECIAL', "Today's Special"), ('OTHERS', 'Others')], default='ALL', max_length=50),
        ),
    ]
