# Generated by Django 6.0.2 on 2026-03-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_menuitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Banner Image'),
        ),
    ]
