# Generated by Django 6.0.2 on 2026-03-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_menuitem_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='Has Sizes/Variants?'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual ₹'),
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual ₹')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Offer ₹')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Qty / Stock')),
                ('is_available', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.menuitem')),
            ],
        ),
    ]
