# Generated by Django 6.0.2 on 2026-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_menuitem_has_variants_alter_menuitem_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('ALL', 'All'), ('BANNER', 'Banner'), ('COMBO MENU', 'Combo Menu'), ('BEST SELLER', 'Best Seller'), ("TODAY'S SPECIAL", "Today's Special"), ('OTHERS', 'Others')], default='ALL', max_length=50),
        ),
    ]
