# Generated by Django 6.0.2 on 2026-03-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
    ]
